### ISSUE TITLE
Source code of filterBam-zlib-ng-2

### ISSUE THREAD

**Issue by xiekunwhy** [harvardinformatics/GenomeAnnotation#1]
Hi,

I am now filtering a large bam file, I found that filterBam cost me a long time to run. Do you want to public the source code of filterBam-zlib-ng-2 ?

Best,
Kun

**Comment by adamfreedman** [comment]
Hi Kun,

We no longer use that piece of code. Mario Stanke informed us that it has some bugs in it. The most recent version of Augustus should have a slightly faster version of filterBam. Furthermore, we have started downsampling bam files --which we create by merging across samples-- to be no bigger than 40-50Gb. As the splice site hints derived from it are just used to train a model that then predicts intron-exon structure across the genome, it really is overkill to supply a bam file of >100Gb ... which is what we did previously and which led to excessively long compute times. Does that make sense?

Best,
Adam

Adam H. Freedman, PhD
Data Scientist
Faculty of Arts & Sciences Informatics Group
Harvard University
38 Oxford St
Cambridge, MA 02138
phone: +001 310 415 7145
________________________________
From: xiekunwhy ***@***.***>
Sent: Tuesday, March 15, 2022 9:33 AM
To: harvardinformatics/GenomeAnnotation ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [harvardinformatics/GenomeAnnotation] Source code of filterBam-zlib-ng-2 (Issue #1)


Hi,

I am know filter an large bam file, I found that filterBam cost me a long time to run. Do you want to public the source code of filterBam-zlib-ng-2 ?

Best,
Kun

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_harvardinformatics_GenomeAnnotation_issues_1&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=MITI_LEJgyr1a24IMFAlSaZIPxMpOUT21T7L3fg4CjA&m=QyIRNgb1gRPXwUC9m57DWpXwYAivHvry8_eTtgD76ws4ZYdW1V19Hoe02e6rv7zV&s=gnBWu3Nx5gklFL3qv_qDBAwW-ZAh1huSic-FSyCZsRw&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADBMMUEK63DOJWES6JKBJTLVACGTHANCNFSM5QYWI52Q&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=MITI_LEJgyr1a24IMFAlSaZIPxMpOUT21T7L3fg4CjA&m=QyIRNgb1gRPXwUC9m57DWpXwYAivHvry8_eTtgD76ws4ZYdW1V19Hoe02e6rv7zV&s=OkCg5GYxtemMLuahl4Zr4d-2ZRGefOBMLEpg5VMfoFU&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=MITI_LEJgyr1a24IMFAlSaZIPxMpOUT21T7L3fg4CjA&m=QyIRNgb1gRPXwUC9m57DWpXwYAivHvry8_eTtgD76ws4ZYdW1V19Hoe02e6rv7zV&s=uLJfd90416UMwpONRJ_EIRnQM_P2FOQES7HC8RBV9cA&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=MITI_LEJgyr1a24IMFAlSaZIPxMpOUT21T7L3fg4CjA&m=QyIRNgb1gRPXwUC9m57DWpXwYAivHvry8_eTtgD76ws4ZYdW1V19Hoe02e6rv7zV&s=vHR6eacPevadVsgGGRyxWLr6yypSQNN1qkSio1aB8kc&e=>.

**Comment by nathanweeks** [comment]
@xiekunwhy FWIW, the filterBam optimizations that were added to the upstream Augustus appeared in https://github.com/Gaius-Augustus/Augustus/pull/308 (which isn't part of a release yet, so Augustus would need to be built from source in order to get a somewhat-faster filterBam)
