### ISSUE TITLE
How to use this pipeline

### ISSUE THREAD

**Issue by lifan18** [harvardinformatics/GenomeAnnotation#6]
Dear authors,

Thank you for your great contribution for this remarkable genome annotation pipeline!

Since there is no other genomeAnnotation pipeline people can follow, your great work means a lot for everyone like me who is new to this area. Although I read your wiki, I still don't know how to use or follow this pipeline. Should I install the related softwares one by one? Could you write a guideline or usage for this pipeline?

Merry Xmas!

**Comment by adamfreedman** [comment]
this isn't a pipeline page. this is a landing page that describes the tools that were evaluated as part of a methods evaluation project ... the paper for which will be posted on biorxiv soon.
